### PR TITLE
Add gmail instructions

### PR DESCRIPTION
**Pull request by samertm**
Created a 'docs' folder, added instructions for setting up @directactioneverywhere.com emails.

### CODE REVIEW

**Comment by linguinee** [comment]
Should there be two folders? One for tech working group docs (those that members will most likely be the ones looking at, e.g. facilitator or scribe instructions) and one for docs we link to users (i.e. tech requests…not sure if these email instructions would be here as well, unless the doc were changed to be a "here's how you do this" vs the "copy-paste this into an email to send to the person" form it's in now).

**Comment by samertm** [comment]
That makes sense to me. They could be 'internal/' (not sure about the
name) and 'docs/'?

On Mon, Dec 14, 2015, at 11:06 PM, Ling-Yi Kung wrote:

> Should there be two folders? One for tech working group docs (those
> that members will most likely be the ones looking at, e.g.
> facilitator or scribe instructions) and one for docs we link to users
> (i.e. tech requests…not sure if these email instructions would be
> here as well, unless the doc were changed to be a "here's how you do
> this" vs the "copy-paste this into an email to send to the person"
> form it's in now).
> 
> — Reply to this email directly or view it on GitHub[1].

Links:
1. https://github.com/directactioneverywhere/notes/pull/3#issuecomment-164664490

**Comment by samertm** [comment]
Split it into two docs and moved them into 'docs'. I kept the gmail linking instructions in the form of an email because it's most likely going to be used that way, and it's easier than asking them to click on a link.

**Comment by linguinee** [comment]
lgtm :ship:

**Pull request merged**
